# bench/commands/make.py
import os
import sys
from pathlib import Path
import click
from rich import print as rprint

DANGEROUS_POSIX = {"/", "/root", "/usr", "/usr/local", "/etc", "/var"}
DANGEROUS_WIN   = {"C:\\", "C:\\Windows", "C:\\Windows\\System32"}

@click.group(help="Scaffold workspaces, sites, and apps.")
def cmd():
    pass

def _is_dangerous(path: Path) -> bool:
    p = str(path.resolve())
    if os.name == "nt":
        p = p.replace("/", "\\")
        return any(p.lower() == d.lower() or p.lower().startswith(d.lower()+"\\") for d in DANGEROUS_WIN)
    return p in DANGEROUS_POSIX

@cmd.command("workspace")
@click.argument("path", required=False, default=".")
@click.option("--force", is_flag=True, help="Allow initializing in risky directories.")
def make_workspace(path: str, force: bool):
    """Create a bench-like workspace skeleton (apps/, env/, config/, logs/, sites/)."""
    root = Path(path).resolve()
    if not force and _is_dangerous(root):
        rprint(f"[red]Refusing to init in risky location:[/] {root}\nUse [yellow]--force[/] to override.")
        sys.exit(2)

    (root / "apps").mkdir(parents=True, exist_ok=True)
    (root / "env").mkdir(parents=True, exist_ok=True)
    (root / "config").mkdir(parents=True, exist_ok=True)
    (root / "logs").mkdir(parents=True, exist_ok=True)
    (root / "sites").mkdir(parents=True, exist_ok=True)

    procfile = root / "Procfile"
    if not procfile.exists():
        procfile.write_text("web: python manage.py runserver 0.0.0.0:8000\n")
    patches = root / "patches.txt"
    if not patches.exists():
        patches.write_text("# patches (one per line)\n")

    rprint(f"[green]Workspace ready:[/] {root}")
    rprint("• apps/  • env/  • config/  • logs/  • sites/  • Procfile  • patches.txt")

@cmd.command("create-app")
@click.argument("name")
@click.option("--apps-dir", default="apps", help="Where to create the app package.")
def create_app(name: str, apps_dir: str):
    """Create a bare Python app package in apps/<name>."""
    base = Path(apps_dir).resolve()
    pkg = base / name
    pkg.mkdir(parents=True, exist_ok=True)
    (pkg / "__init__.py").write_text(f'__all__ = []\n__version__ = "0.0.1"\n')
    (pkg / "README.md").write_text(f"# {name}\n\nGenerated by bench make create-app\n")
    rprint(f"[green]App created:[/] {pkg}")

@cmd.command("new-site")
@click.argument("sitename")
@click.option("--sites-dir", default="sites", help="Parent directory for sites.")
def new_site(sitename: str, sites_dir: str):
    """Create a site folder (no framework opinion yet; just scaffolding)."""
    root = Path(sites_dir).resolve()
    site = root / sitename
    (site / "backend").mkdir(parents=True, exist_ok=True)
    (site / "assets").mkdir(parents=True, exist_ok=True)
    (site / "config").mkdir(parents=True, exist_ok=True)
    (site / "logs").mkdir(parents=True, exist_ok=True)
    (site / "README.md").write_text(f"# Site: {sitename}\n")
    rprint(f"[green]Site created:[/] {site}")
